api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='apihome'),
]

blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'cart'

urlpatterns = [
    path('', views.function, name='bloghome'),
    path('about/', views.about, name='about'),
    path('contact us/', views.contact, name="contact"),
    path('tracker/', views.tracker, name='TrackingStatus'),
    path('search/', views.search, name='Search'),
    path('checkout/', views.checkout, name='Checkout'),
    path('product/<int:myid>', views.prod, name='Product'),
    path('category/<str:category>', views.category, name="category"),
    path('sub category/<str:sub_category>', views.sub_category, name="sub_category"),
    path('cart/', views.view_cart, name="view_cart"),
    path('add/<int:item_id>', views.add_to_cart, name="add_to_cart"),
    path('remove/<int:item_id>', views.remove_from_cart, name="remove_from_cart"),
    path('delete/<int:item_id>', views.delete_from_cart, name="delete_from_cart"),
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup_view, name="signup"),
    path("profile/", views.profile, name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("profile/change_password/", auth_views.PasswordChangeView.as_view(template_name="registration/change_password.html"), name="change_password"),
    path("profile/change_password/done/", auth_views.PasswordChangeDoneView.as_view(template_name="registration/password_change_done.html"), name="password_change_done"),
]

project2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime
from django.core.validators import MinValueValidator
import os
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from .constants import categories


class Product(models.Model):
    product_name = models.CharField(max_length=100, default='')
    category = models.CharField(
        max_length=30,
        choices=[(key, key) for key in categories.keys()],
        default='Other'
    )
    sub_category = models.CharField(max_length=50, default='', blank=True)
    price = models.IntegerField(validators=[MinValueValidator(0)])
    number_of_stock = models.IntegerField(validators=[MinValueValidator(0)])
    description = models.CharField(max_length=400, default='')
    max_order_quantity = models.IntegerField(validators=[MinValueValidator(1)], default=10)
    published_date = models.DateField(default=datetime.date.today)
    image = models.FileField(
        upload_to='blog/images/',
        default='',
        help_text='Recommended image size: 230×200 pixels'
    )

    def __str__(self):
        return self.product_name

    def delete(self, *args, **kwargs):
        if self.image and os.path.isfile(self.image.path):
            os.remove(self.image.path)
        super().delete(*args, **kwargs)   


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quantity} x {self.product.name}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"
    
    
    
    
    

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Product



class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    class Media:
        js = ('admin/js/subcategory.js',)
        
        

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Product, CartItem, Profile
from math import ceil
from django.contrib.auth import login
from .forms import SignUpForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def index(cart_quantities):
    allProds = []
    catprods = Product.objects.values('category', 'id')
    cats = {item['category'] for item in catprods}
    sorted_cats = sorted(cats)
    
    for cat in sorted_cats:
        prod = Product.objects.filter(category=cat).order_by('product_name')

        for product in prod:
            product.adjusted_stock = max(product.number_of_stock - cart_quantities.get(product.id, 0), 0)
        
        n = len(prod)
        nSlides = n // 4 + ceil((n / 4) - (n // 4))
        allProds.append([prod, range(1, nSlides), nSlides])
    
    return {'allProds': allProds}

def get_cart_quantities(request):
    if request.user.is_authenticated:
        cart_items = CartItem.objects.filter(user=request.user)
        return {item.product.id: item.quantity for item in cart_items}
    else:
        cart = request.session.get('view_cart', {})
        return {int(k): int(v) for k, v in cart.items()}

def get_adjusted_stock(product, cart_quantities):
    quantity_in_cart = cart_quantities.get(product.id, 0)
    return max(product.number_of_stock - quantity_in_cart, 0)

def function(request):
    cart_quantities = get_cart_quantities(request)
    params = index(cart_quantities)
    
    context = {**params, 'cart_quantities': cart_quantities}
    return render(request, 'blog/home.html', context)


def about(request):
    cart_quantities = get_cart_quantities(request)
    params = index(cart_quantities)
    return render(request, 'blog/about.html', params)

def contact(request):
    cart_quantities = get_cart_quantities(request)
    params = index(cart_quantities)
    return render(request, 'blog/contact.html',params)


def prod(request, myid):
    product = get_object_or_404(Product, id=myid)
    cart_quantities = get_cart_quantities(request)
    params = index(cart_quantities)
    quantity_in_cart = cart_quantities.get(product.id, 0)
    product.number_of_stock -= quantity_in_cart
    
    quantity_range = range(1, (product.max_order_quantity - quantity_in_cart) + 1)
    
    param = {'product': product, 'cart_quantities': cart_quantities, 'quantity_range': quantity_range}
    context = {**params, **param}
    return render(request, 'blog/product.html', context)


def category(request, category):  
    allProd = []
    scatprod = Product.objects.values('sub_category', 'id').filter(category=category)
    cats = {item['sub_category'] for item in scatprod}
    sorted_cats = sorted(cats)

    for cat in sorted_cats:
        prod = Product.objects.filter(sub_category=cat, category=category).order_by('product_name')
        n = len(prod)
        nSlide = n // 4 + ceil((n / 4) - (n // 4))
        allProd.append([prod, range(1, nSlide), nSlide])
        cart_quantities = get_cart_quantities(request)
        for product in prod:
            product.adjusted_stock = max(product.number_of_stock - cart_quantities.get(product.id, 0), 0)
    params = index(cart_quantities)
    param = {
        'allProd': allProd, 'category': category, 'cart_quantities': cart_quantities
        }
    
    context = {**param, ** params}
    return render(request, 'blog/category.html', context)


def sub_category(request, sub_category):
    products = Product.objects.filter(sub_category=sub_category)
    category = products.first().category if products.exists() else ''
    n = len(products)
    nSlides = ceil(n / 4)
    
    cart_quantities = get_cart_quantities(request)
    for product in products:
        product.adjusted_stock = max(product.number_of_stock - cart_quantities.get(product.id, 0), 0)
    params = index(cart_quantities)
    par = {
        'products': products,
        'sub_category': sub_category,
        'category': category,
        'nSlides': nSlides,
        'cart_quantities': cart_quantities
    }
    
    con = {**params, **par}
    return render(request, 'blog/sub_category.html', con)


def view_cart(request):
    if not request.user.is_authenticated:
        messages.warning(request, "You need to log in to view items to the cart.")
        return redirect('/login/')
    cart_items = CartItem.objects.filter(user=request.user)
    total_price = sum(item.product.price * item.quantity for item in cart_items)
    total_quantity = sum(item.quantity for item in cart_items)
    cart_quantities = {item.product.id: item.quantity for item in cart_items}
    cart_quantity = get_cart_quantities(request)
    params = index(cart_quantity)
    for item in cart_items:
        item.product.adjusted_stock = max(item.product.number_of_stock - cart_quantities.get(item.product.id, 0), 0)
        
    p = {'cart_items': cart_items, 'total_price': total_price, 'cart_quantities': cart_quantities, 'total_quantity': total_quantity}
    c = {**p, **params}
    c.update(params)
    return render(request, 'blog/cart.html', c)


def add_to_cart(request, item_id):
    if not request.user.is_authenticated:
        messages.warning(request, "You need to log in to add items to the cart.")
        return redirect('/login/')
    
    cart_item, created = CartItem.objects.get_or_create(
        user=request.user,
        product_id=item_id,
        defaults={'quantity': 1}
    )
    if not created:
        cart_item.quantity += 1
        cart_item.save()
    referer = request.META.get('HTTP_REFERER', '/')
    return HttpResponseRedirect(referer)


def remove_from_cart(request, item_id):
    if not request.user.is_authenticated:
        messages.warning(request, "You need to log in to remove items to the cart.")
        return redirect('/login/')
    
    cart_item = CartItem.objects.get(user=request.user, product_id=item_id)
    if cart_item.quantity == 1:
        cart_item.delete()
    else:
        cart_item.quantity -= 1
        cart_item.save()
    referer = request.META.get('HTTP_REFERER', '/')
    return HttpResponseRedirect(referer)


def delete_from_cart(request, item_id):
    if not request.user.is_authenticated:
        messages.warning(request, "You need to log in to delete items to the cart.")
        return redirect('/login/')
    
    cart_item = CartItem.objects.get(user=request.user, product_id=item_id)
    cart_item.delete()
    referer = request.META.get('HTTP_REFERER', '/')
    return HttpResponseRedirect(referer)

def signup_view(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('cart:bloghome')
    else:
        form = SignUpForm()
    return render(request, "registration/signup.html", {"form": form})


def profile(request):
    if not request.user.is_authenticated:
        messages.warning(request, "You need to log in to view your profile.")
        return redirect('/login/')
    
    cart_quantities = get_cart_quantities(request)
    params = index(cart_quantities)
    return render(request, 'blog/profile.html', {'user': request.user, 'cart_quantities': cart_quantities, **params})

def edit_profile(request):
    user = request.user
    profile, created = Profile.objects.get_or_create(user=user)
    if request.method == 'POST':
        user = request.user
        user.first_name = request.POST.get('full_name', user.first_name)
        user.username = request.POST.get('username', user.username)
        user.email = request.POST.get('email', user.email)
        user.profile.phone_number = request.POST.get('phone_number', user.profile.phone_number)
        user.save()
        messages.success(request, 'Your profile has been updated successfully!')
        return redirect('cart:profile')
    return render(request, 'blog/edit_profile.html', {'user': request.user})


def checkout(request):
    if not request.user.is_authenticated:
        messages.warning(request, "You need to log in to buy items.")
        return redirect('/login/')
    cart_items = CartItem.objects.filter(user=request.user)
    
    cart_quantities = get_cart_quantities(request)
    params = index(cart_quantities)
    
    return render(request, 'blog/checkout.html', params)

def search(request):
    query = request.GET.get('q', '').strip()
    cart_quantities = get_cart_quantities(request)
    params = index(cart_quantities)

    if len(query) > 78:
        messages.warning(request, "Please enter a query with less than 78 characters.")
        return render(request, 'blog/search.html', {**params, 'cart_quantities': cart_quantities})

    products = Product.objects.filter(product_name__icontains=query) if query else Product.objects.none()
    for product in products:
        product.adjusted_stock = max(product.number_of_stock - cart_quantities.get(product.id, 0), 0)
        
    if query and not products.exists():
        messages.warning(request, f"No results found for '{query}'.")

    context = {
        'search_results': products,
        'query': query,
        'cart_quantities': cart_quantities,
        **params,
    }

    return render(request, 'blog/search.html', context)


def tracker(request):
    return HttpResponse("Tracker")

templates/blog/about.html
{% extends "blog/basic.html" %}

{% block title %}About{% endblock %}

{% block body %}
{% load static %}

<div class="jumbotron jumbotron-fluid" style="width: 800px; margin:0 auto; ">
<div class="container">
      <center><h1 class="mt-0">📝 About Us</h1></center>
      <div align="center">
      <img src="{% static 'blog/about.jpeg' %}" style="height: 250px;" class="align-self-center mr-3">
      </div>
<hr>

      <p class="lead">Welcome to Blog, your go-to platform for insightful articles, expert opinions, and thought-provoking content across a wide range of topics. Whether you're here to stay updated on the latest trends, learn something new, or simply enjoy a good read, we've got something for everyone.</p>

    <p class="lead">At Blog, we believe in the power of words to inform, inspire, and connect people. Our mission is to deliver high-quality content that is both informative and engaging. From lifestyle and technology to personal development and current affairs, our goal is to spark conversations and provide value to our readers.</p>
        
    <p class="lead">Our team is made up of passionate writers, creators, and thinkers who are dedicated to making Blog a trusted source of knowledge and creativity. Thank you for being a part of our journey.</p>
        
    <p class="lead">Stay curious. Stay inspired.</p>
    </div>
  </div>




{% endblock %}

templates/blog/cart.html
<!doctype html>
<html lang="en">

    {% load static %}
    {% load humanize %}

<head>
    <title>Cart</title>

    <link rel="icon" href="{% static 'blog/images.png' %}" type="image/png">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>Document</title>

</head>

<body style="background-color:rgb(173, 166, 180)">
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:rgba(13, 0, 192, 0.37)">
        <a class="navbar-brand" href="/"><img src="{% static 'blog/images.png' %}" height=20>Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about/">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/contact us/">Contact Us</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Categories
              </a>
              <div class="dropdown-menu">
              {% for product, range, nSlides in allProds %}
                <a class="dropdown-item" href="/category/{{product.0.category}}">{{product.0.category}}</a>
              {% endfor %}
              </div>
            </li>
            <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'cart:Search' %}">
              <input class="form-control mr-sm-2" value="{{query}}" name="q" type="text" placeholder="Search Product" aria-label="Search" style="width: 1214px;">              
              <button id="search" type="submit">Search</button>
            </form>
            <a href="/cart/">
              <li>
                <a class="nav-link active" href="/cart/">Cart</a>
              </li>
            </a>
            <li class="nav-item">
              <a class="nav-link" href="/profile/">Profile</a>
          </li>
            <li class="nav-item">
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}" id="logout">Logout</a>
            {% else %}
              <a class="nav-link" href="{% url 'login' %}" id="login">Login</a>
            {% endif %}
            </li>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </nav><br><br>

    <div class="product-list">




    <style>

      #search {
        background-color: rgb(56, 81, 165);
        color: white;
        height: 38px;
        width: 80px;
        border-radius: 4px;
      }
      
      #logout {
        color:rgba(0, 0, 0, 0.5);
      }
      #login {
        color:rgba(255, 255, 255, 0.7);
      }
      #logout:hover {
        color:rgba(0, 0, 0, 0.8);
      }
      #login:hover {
        color:rgba(255, 255, 255, 1);
      }

    .product-list {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        list-style: nonne;
        padding: 0;
    }

    .product-item {
        flex: 1;
        margin: 10px;
        border: 1px solid #ccc;
        padding: 10px;
        text-align: center;
    }

    .product-item img {
        width: 200px;
        height: 250px;
    }


    .product-item {
      border: 1px solid #ddd;
      padding: 16px;
      margin: 16px;
      width: 250px;
      display: inline-block;
      vertical-align: top;
      text-align: center;
      background-color:rgb(133, 133, 141);
      border-radius: 8px;
    }
    
    
    .divider {
      margin: 10px 0;
      border: 1px solid #000;
    }
    
    .product-price p,
    .product-name p {
      color: rgba(0, 0, 0, 0.65);
      margin: 8px 0;
    }
    
    .product-price p {
      font-size: 1.5rem;
    }
    
    .product-name p {
      font-size: 1rem;
      color: rgba(0, 0, 0, 0.65);
      height: 2.5rem;
      line-height: 1.25rem;
      display: -webkit-box;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    
    a {
      color:rgba(0, 0, 0, 0.69);
      text-decoration: none;
    }
    
    a:hover {
      color:rgb(0, 0, 0);
      text-decoration: none;
    }

    #plus {
      background-color:rgb(56, 81, 165);
      color: white;
      border: none;
      border-radius: 4px;
      margin-right: 2rem;
      height: 40px;
      width: 40px;
    }

    #plus:hover {
      background-color:rgb(33, 48, 97);
    }

    #minus {
      background-color:rgb(165, 56, 56);
      color: white;
      border: none;
      border-radius: 4px;
      height: 40px;
      width: 40px;
    }

    #minus:hover {
      background-color:rgb(97, 33, 33);
    }

    #trash {
      background-color:rgb(165, 56, 56);
      color: white;
      border: none;
      border-radius: 4px;
      height: 40px;
      width: 40px;
    }

    #trash:hover {
      background-color:rgb(97, 33, 33);
    }

    #remove{
      background-color:rgba(41, 35, 35, 0.42);
      color: white;
      border: none;
      border-radius: 4px;
      height: 40px;
      width: 40px;
    }

    #remove:hover{
      background-color: rgb(41, 35, 35);
    }


    </style>




    {% for item in cart_items %}
    <div class="product-item">
      <a href="/product/{{item.product.id}}">
        <div class="product-image">
        <img src='/media/{{item.product.image}}'>
        </div>
        <hr class="divider">
        <div class="product-price">
        <p style="color:rgba(0, 0, 0, 0.65); font-size: 1.5rem">Price: <b>₹{{item.product.price|intcomma}}</b></p>
        </div>
        <div class="product-name">
        <p style="color:rgba(0, 0, 0, 0.65); font-size: 1rem"><b>{{ item.product.product_name }}</b></p>
        </div>
        </a>
        {% if item.quantity == 1 %}
        <form action="{% url 'cart:remove_from_cart' item.product.id %}" method="post" style="display:inline;">
          {% csrf_token %}
          <button type="submit" id="trash">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
              <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
            </svg>
          </button>
        </form>
        {% else %}
        <form action="{% url 'cart:remove_from_cart' item.product.id %}" method="post" style="display:inline;">
          {% csrf_token %}
          <button type="submit" id="minus">−</button>
        </form>
        {% endif %}
        <b>{{ item.quantity }}</b>
        <span>{{ cart_quantity }}</span>
        {% if item.quantity < item.product.max_order_quantity %}
          {% if item.product.adjusted_stock != 0 %}
        
            <form action="{% url 'cart:add_to_cart' item.product.id %}" method="post" style="display:inline;">
              {% csrf_token %}
              <button type="submit" id="plus">+</button>
            </form>
          {% endif %}
        {% else %}(max)
        {% endif %}
        <form action="{% url 'cart:delete_from_cart' item.product.id %}" method="post" style="display:inline;">
          {% csrf_token %}
          <button type="submit" id="remove">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
              <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
            </svg>
          </button>
        </form> 
    </div>
    {% empty %}

    <b><p style="color:rgb(35, 34, 39); font-size: 2rem">Your cart is empty.</p></b>

    {% endfor %}

    </div><br>


<div class="jumbotron" style="background: rgb(133, 127, 139)">
    <center>
        <p style="color:rgb(35, 34, 39); font-size: 1.5rem">Total Price: <b><u>₹{{ total_price|intcomma }}</u></b></p>
        <p style="color:rgb(35, 34, 39); font-size: 1.5rem">Total Items: <b><u>{{ total_quantity }}</u></b></p>
            {% if total_quantity %}
            <a href="/checkout/">
              <button type="submit" class="btn btn-primary btn-lg active" style="background-color: rgb(33, 48, 97)">Buy Now</button>
            </a>
            {% endif %}
        <button class="btn btn-secondary btn-lg active" onclick="history.back()">Continue Shopping</button>
    </center>
</div>




    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script> 
</body>

</html>

templates/blog/checkout.html
{% extends "blog/basic.html" %}

{% block title %}About{% endblock %}

{% block body %}
{% load static %}

<div class="jumbotron jumbotron-fluid" style="width: 800px; margin:0 auto; ">
<div class="container">
      <center><h1 class="mt-0">This is checkout</h1></center>

<hr>

</div>
</div>




{% endblock %}

templates/blog/profile.html
{% extends "blog/basic.html" %}

{% block title %}Profile{% endblock %}

{% block body %}
<div class="jumbotron jumbotron-fluid" style="width: 800px; margin:0 auto;">
    <div class="container">
        <center><h1 class="mt-0">Profile</h1></center>
        <hr>
        <p class="lead">👋 Hello, {{ user.get_full_name }}</p>
        <p><strong>Full Name:</strong> {{ user.get_full_name }}</p>
        <p><strong>Email:</strong> {{ user.email }}</p>
        <p><strong>Phone Number:</strong> {{ user.profile.phone_number|default:"Not provided" }}</p>
        <hr>
        <a href="{% url 'cart:edit_profile' %}" class="btn btn-primary">Edit Profile</a>
        <a href="{% url 'cart:change_password' %}" class="btn btn-warning">Change Password</a>
    </div>
</div>
{% endblock %}